[package]
name = "keidai"
version = "0.1.0"
edition.workspace = true

[features]
default = []

[lib]
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
postcard = { workspace = true }
quinn = { workspace = true }
serde = "1.0.229"
tokio = { workspace = true }
zerocopy = { workspace = true }
